[build]
command = "npm run build"
publish = "dist"
framework = "vite"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/proxy/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 404
