name = "trackmax-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
# Default target API; can be overridden in Cloudflare dashboard.
TARGET_API_BASE = "http://35.230.168.225:8082/api"
# Fallback proxy URL (Netlify)
FALLBACK_PROXY_URL = "https://dashboard-trackmax.netlify.app/.netlify/functions/proxy"
